apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: '*'
    kind: ClusterRoleBinding
  - group: '*'
    kind: ClusterRole
  - group: '*'
    kind: CustomResourceDefinition
  destinations:
  - namespace: postgres-operator
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/Yaroksito/postgres-operator-deployment.git
