apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  project: postgres-db
  source:
    path: install
    repoURL: https://github.com/Yaroksito/postgres-operator-5.0.3.git
    targetRevision: HEAD
